---
- name: 'Instala pacotes do sistema operacional'
  apt:
    name:
      - php7.2
      - apache2
      - libapache2-mod-php7.2
      - php7.2-gd
      - libssh-4 
      - php7.2-mysql
    state: latest
  become: yes